kind: pipeline
type: docker
name: default

steps:
  - name: yarn install
    image: node:16
    volumes:
      - name: cache
        path: /drone/src/node_modules
    commands:
      - yarn
  - name: yarn build
    image: node:16
    volumes:
      - name: cache
        path: /drone/src/node_modules
    environment:
      REACT_APP_NAME:
        from_secret: REACT_APP_NAME
    commands:
      - yarn build
  - name: rsync
    image: drillster/drone-rsync
    settings:
      user: root
      key:
        from_secret: ssh_key
      hosts:
        - 172.22.253.15
      source: ./build/*
      delete: true
      target: /var/www/dogeow

trigger:
  event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/dogeow/cache

